#
# arch/blackfin/mach-bf527/boards/Makefile
#

obj-$(CONFIG_BFIN527_EZKIT)            += ezkit.o
obj-$(CONFIG_BFIN527_BLUETECHNIX_CM)   += cm_bf527.o
obj-$(CONFIG_BFIN526_EZBRD)            += bf526_ezbrd.o
