# Blackfin Platform Support
snd-soc-bf5xx-objs := bf5xx-pcm.o
snd-soc-bf5xx-ac97-objs := bf5xx-ac97.o bf5xx-sport.o

obj-$(CONFIG_SND_BF5XX_SOC) += snd-soc-bf5xx.o
obj-$(CONFIG_SND_BF5XX_SOC_AC97) += snd-soc-bf5xx-ac97.o

# Blackfin Machine Support
snd-soc-bf548-ezkit-objs := bf548-ezkit.o
snd-soc-bf5xx-board-objs := bf5xx-board.o

obj-$(CONFIG_SND_BF5XX_SOC_BF548_EZKIT) += snd-soc-bf548-ezkit.o
obj-$(CONFIG_SND_BF5XX_SOC_BF5xx) += snd-soc-bf5xx-board.o
