# Blackfin Platform Support
snd-soc-bf5xx-objs := bf5xx-pcm.o
snd-soc-bf5xx-ac97-objs := bf5xx-ac97.o bf5xx-sport.o
snd-soc-bf5xx-i2s-objs := bf5xx-i2s.o bf5xx-sport.o

obj-$(CONFIG_SND_BF5XX_SOC) += snd-soc-bf5xx.o
obj-$(CONFIG_SND_BF5XX_SOC_AC97) += snd-soc-bf5xx-ac97.o
obj-$(CONFIG_SND_BF5XX_SOC_I2S) += snd-soc-bf5xx-i2s.o

# Blackfin Machine Support
snd-soc-bf548-ezkit-objs := bf548-ezkit.o
snd-soc-bf5xx-board-objs := bf5xx-board.o
snd-soc-bf5xx-wm8750-objs := bf5xx-wm8750.o
snd-soc-bf5xx-wm8731-objs := bf5xx-wm8731.o

obj-$(CONFIG_SND_BF5XX_SOC_BF548_EZKIT) += snd-soc-bf548-ezkit.o
obj-$(CONFIG_SND_BF5XX_SOC_BF5xx) += snd-soc-bf5xx-board.o
obj-$(CONFIG_SND_BF5XX_SOC_WM8750) += snd-soc-bf5xx-wm8750.o
obj-$(CONFIG_SND_BF5XX_SOC_WM8731) += snd-soc-bf5xx-wm8731.o
