# Blackfin Platform Support
snd-bf5xx-ac97-objs := bf5xx-ac97-pcm.o
snd-bf5xx-i2s-objs := bf5xx-i2s-pcm.o
snd-bf5xx-tdm-objs := bf5xx-tdm-pcm.o
snd-soc-bf5xx-sport-objs := bf5xx-sport.o
snd-soc-bf5xx-ac97-objs := bf5xx-ac97.o
snd-soc-bf5xx-i2s-objs := bf5xx-i2s.o
snd-soc-bf5xx-tdm-objs := bf5xx-tdm.o

obj-$(CONFIG_SND_BF5XX_AC97) += snd-bf5xx-ac97.o
obj-$(CONFIG_SND_BF5XX_I2S) += snd-bf5xx-i2s.o
obj-$(CONFIG_SND_BF5XX_TDM) += snd-bf5xx-tdm.o
obj-$(CONFIG_SND_BF5XX_SOC_SPORT) += snd-soc-bf5xx-sport.o
obj-$(CONFIG_SND_BF5XX_SOC_AC97) += snd-soc-bf5xx-ac97.o
obj-$(CONFIG_SND_BF5XX_SOC_I2S) += snd-soc-bf5xx-i2s.o
obj-$(CONFIG_SND_BF5XX_SOC_TDM) += snd-soc-bf5xx-tdm.o

# Blackfin Machine Support
snd-ad183x-objs := bf5xx-ad183x.o
snd-ad1980-objs := bf5xx-ad1980.o
snd-ssm2602-objs := bf5xx-ssm2602.o
snd-ad73311-objs := bf5xx-ad73311.o
snd-ad193x-objs := bf5xx-ad193x.o
snd-adau1371-objs := bf5xx-adau1371.o
snd-adau1761-objs := bf5xx-adau1761.o
snd-adau1361-objs := bf5xx-adau1361.o
snd-adau1381-objs := bf5xx-adau1381.o
snd-adau1373-objs := bf5xx-adau1373.o
snd-adav80x-objs := bf5xx-adav80x.o

obj-$(CONFIG_SND_BF5XX_SOC_AD183X) += snd-ad183x.o
obj-$(CONFIG_SND_BF5XX_SOC_AD1980) += snd-ad1980.o
obj-$(CONFIG_SND_BF5XX_SOC_SSM2602) += snd-ssm2602.o
obj-$(CONFIG_SND_BF5XX_SOC_AD73311) += snd-ad73311.o
obj-$(CONFIG_SND_BF5XX_SOC_AD193X) += snd-ad193x.o
obj-$(CONFIG_SND_BF5XX_SOC_ADAU1371) += snd-adau1371.o
obj-$(CONFIG_SND_BF5XX_SOC_ADAU1761) += snd-adau1761.o
obj-$(CONFIG_SND_BF5XX_SOC_ADAU1361) += snd-adau1361.o
obj-$(CONFIG_SND_BF5XX_SOC_ADAU1381) += snd-adau1381.o
obj-$(CONFIG_SND_BF5XX_SOC_ADAU1373) += snd-adau1373.o
obj-$(CONFIG_SND_BF5XX_SOC_ADAV80X) += snd-adav80x.o
