#
# Makefile for the blackfin 53x sport/spi connected ad1836
#

snd-ad1836-objs  := ad1836_spi.o bf53x_sport.o ad1836.o
snd-ad73322-objs := ad73322.o bf53x_sport.o

obj-$(CONFIG_SND_BLACKFIN_AD1836)	+= snd-ad1836.o
obj-$(CONFIG_SND_BFIN_AD73322)		+= snd-ad73322.o
