#
# Makefile for the blackfin 53x sport/spi connected ad1836
#

snd-ad1836-objs  := ad1836_spi.o bf53x_sport.o ad1836.o
snd-ad73311-objs := ad73311.o bf53x_sport.o

obj-$(CONFIG_SND_BLACKFIN_AD1836)	+= snd-ad1836.o
obj-$(CONFIG_SND_BFIN_AD73311)		+= snd-ad73311.o
