
bfin-cam-sensor-$(CONFIG_VS6524)  := vs6524.o
bfin-cam-sensor-$(CONFIG_VS6624)  := vs6624.o
bfin-cam-sensor-$(CONFIG_MT9V022) := mt9v022.o
bfin-cam-sensor-$(CONFIG_OV9655) := ov9655.o
bfin-cam-sensor-$(CONFIG_ADV7183B):= adv7183b.o
obj-$(CONFIG_VIDEO_BLACKFIN_CAM)  := blackfin_cam.o $(bfin-cam-sensor-y)
obj-$(CONFIG_VIDEO_BLACKFIN_MT9M001) += mt9m001.o
