bfin_video_capture-objs := bfin_capture.o ppi.o
bfin_video_display-objs := bfin_display.o ppi.o
obj-$(CONFIG_VIDEO_BLACKFIN_CAPTURE) += bfin_video_capture.o
obj-$(CONFIG_VIDEO_BLACKFIN_DISPLAY) += bfin_video_display.o
