obj-$(CONFIG_VIDEO_BLACKFIN_CAM) += blackfin_cam.o

ifeq ($(CONFIG_VS6524),y)
  obj-$(CONFIG_VIDEO_BLACKFIN_CAM)	+= vs6524.o
endif

ifeq ($(CONFIG_VS6624),y)
  obj-$(CONFIG_VIDEO_BLACKFIN_CAM)	+= vs6624.o
endif

ifeq ($(CONFIG_MT9V022),y)
  obj-$(CONFIG_VIDEO_BLACKFIN_CAM)	+= mt9v022.o
endif

obj-$(CONFIG_VIDEO_BLACKFIN_MT9M001) += mt9m001.o

