# $Id: Makefile 2394 2006-11-02 07:11:55Z magicyang $
# Makefile for the Sun Boot PROM interface library under
# Linux.
#

obj-y := init.o console.o printf.o  misc.o
#bootstr.o init.o misc.o segment.o console.o printf.o
